name: server_ci

on: [ pull_request, push ]

jobs:
  check-code:
    name: check-code
    runs-on: ubuntu-latest

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19
      
      - name: Code Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Linting        
        run: npm run lint
        working-directory: ./server

      - name: Type Checking        
        run: npm run type-check
        working-directory: ./server