name: server_ci

on: [ pull_request, push ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - working-directory: ./server
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm run lint
